export const SOURCES = [
  // Allegan County
  { county: 'Allegan', name: 'Allegan Township Planning Commission', url: 'https://allegantownship.org/planning-commission/' },
  { county: 'Allegan', name: 'Casco Township Planning Commission', url: 'https://www.cascotownship.info/meetings---planning-commission.html' },
  { county: 'Allegan', name: 'Cheshire Township Planning Commission', url: 'https://cheshiretownshipmi.gov/minutes.html' },
  { county: 'Allegan', name: 'Clyde Township Planning Commission', url: 'https://clydetwp.com/' },
  { county: 'Allegan', name: 'Dorr Township Planning Commission', url: 'https://dorrtownshipmi.gov/-Minutes-Agendas/Planning-Commission' },
  { county: 'Allegan', name: 'Fillmore Township Planning Commission', url: 'https://fillmoretownship.org/board-minutes/' },
  { county: 'Allegan', name: 'Ganges Township Planning Commission', url: 'https://www.gangestownship.org/Planning-Commission-Meetings-Archive.html' },
  { county: 'Allegan', name: 'Gun Plain Township Planning Commission', url: 'https://www.gunplain.org/meeting-minutes-and-agendas/' },
  { county: 'Allegan', name: 'Heath Township Planning Commission', url: 'https://heathtownship.net/' },
  { county: 'Allegan', name: 'Hopkins Township Planning Commission', url: 'https://www.hopkinstownship.org/board-minutes/' },
  { county: 'Allegan', name: 'Laketown Township Planning Commission', url: 'https://laketowntwp.org/boards-commissions/' },
  { county: 'Allegan', name: 'Lee Township Planning Commission', url: 'http://www.leetwp.org/meetingminutes.htm' },
  { county: 'Allegan', name: 'Leighton Township Planning Commission', url: 'https://leightontownship.org/meetings-minutes/' },
  { county: 'Allegan', name: 'Manlius Township Planning Commission', url: 'https://www.manliustwp.org/boardmeetings' },
  { county: 'Allegan', name: 'Martin Township Planning Commission', url: 'https://www.martintownship.org/' },
  { county: 'Allegan', name: 'Monterey Township Planning Commission', url: 'https://www.montereytownship.org/' },
  { county: 'Allegan', name: 'Otsego Township Planning Commission', url: 'https://www.otsegotownship.org/building-planning-and-zoning/' },
  { county: 'Allegan', name: 'Overisel Township Planning Commission', url: 'https://overiseltownship.org/planning-commission/' },
  { county: 'Allegan', name: 'Salem Township Planning Commission', url: 'https://salemtownship.org/planning-commission' },
  { county: 'Allegan', name: 'Saugatuck Township Planning Commission', url: 'https://saugatucktownshipmi.gov/saugatuck-township-local-government/packets-agendas-minutes/agendas/' },
  { county: 'Allegan', name: 'Trowbridge Township Planning Commission', url: 'https://trowbridgetownship.org/' },
  { county: 'Allegan', name: 'Valley Township Planning Commission', url: 'https://valleytwp.org/minutes.htm' },
  { county: 'Allegan', name: 'Watson Township Planning Commission', url: 'https://watsontownshipmi.gov/' },
  { county: 'Allegan', name: 'Wayland Township Planning Commission', url: 'https://waytwp.org/departments/zoning/' },
  { county: 'Allegan', name: 'City of Allegan Planning Commission', url: 'https://www.cityofallegan.org/government/planning_commission.php' },

  // Ottawa County
  { county: 'Ottawa', name: 'Allendale Charter Township Planning Commission', url: 'https://allendalemi.gov/planning-commission/' },
  { county: 'Ottawa', name: 'Blendon Township Planning Commission', url: 'https://www.blendontownship-mi.gov/planning-commission/' },
  { county: 'Ottawa', name: 'Chester Township Planning Commission', url: 'https://www.chester-twp.org/documents/' },
  { county: 'Ottawa', name: 'Crockery Township Planning Commission', url: 'https://crockerytownship.gov/planning-commission/' },
  { county: 'Ottawa', name: 'Georgetown Charter Township Planning Commission', url: 'https://www.gtwp.com/155/Planning-Commission' },
  { county: 'Ottawa', name: 'Grand Haven Charter Township Planning Commission', url: 'https://ghtmi.gov/boards/planning-commission/' },
  { county: 'Ottawa', name: 'Holland Charter Township Planning Commission', url: 'https://www.hct.holland.mi.us/agendas-minutes/planning-commission' },
  { county: 'Ottawa', name: 'Jamestown Charter Township Planning Commission', url: 'https://twp.jamestown.mi.us/government/boards-and-minutes/planning-commission-agendas-minutes/' },
  { county: 'Ottawa', name: 'Olive Township Planning Commission', url: 'https://www.olivetownship.org/document-category/pcminutes/' },
  { county: 'Ottawa', name: 'Park Township Planning Commission', url: 'https://webgen1files1.revize.com/parktwpmi/Document_Center/Meeting%20Agenda_Minutes%20%26%20Packets/Planning%20Commission/' },
  { county: 'Ottawa', name: 'Polkton Charter Township Planning Commission', url: 'https://polktontownship.com/planning-commission/' },
  { county: 'Ottawa', name: 'Port Sheldon Township Planning Commission', url: 'https://www.portsheldontwp.org/planning-commission/' },
  { county: 'Ottawa', name: 'Robinson Township Planning Commission', url: 'https://robinsontwpmi.gov/' },
  { county: 'Ottawa', name: 'Spring Lake Township Planning Commission', url: 'https://springlaketwp.org/board/planning-commission/' },
  { county: 'Ottawa', name: 'Tallmadge Charter Township Planning Commission', url: 'https://tallmadge.com/minutes-agendas/' },
  { county: 'Ottawa', name: 'Wright Township Planning Commission', url: 'http://wrighttownshipottawami.gov/' },
  { county: 'Ottawa', name: 'Zeeland Charter Township Planning Commission', url: 'https://zeelandchartertwpmi.documents-on-demand.com/' },
];
